### ISSUE TITLE
Auto-close only private tabs

### ISSUE THREAD

**Issue by egl85** [igorlogius/auto-close-tabs#1]
Could you please add an option to auto-close only Private Browsing tabs?

**Comment by igorlogius** [comment]
Sure.  ... and done in version 1.5.7

![snip_20221117-225317](https://user-images.githubusercontent.com/67047467/202568105-6705b706-ae2d-4448-8c48-405ec1e55cbb.png)

Remeber to grant to addon "Run in Private Window" permission otherwise it can not access the Private Window scope and checking the option will have no effect. 

ref. 
![snip_20221117-225350](https://user-images.githubusercontent.com/67047467/202568061-fcaa49df-71c5-4e19-ab4b-0fdc867feae8.png)

Have fun.
