### ISSUE TITLE
Tabs not closing

### ISSUE THREAD

**Issue by cecton** [igorlogius/auto-close-tabs#4]
**Describe the bug**

I have been using it since early January and only 4 tabs have been closed. I know because I have set the "bookmark folder to save tabs".

**To Reproduce**

This is one of my session where not a single tab has been closed despite the small amount of days:

(see screenshots)

Currently probably 30-40 tabs opened. Some very old.

**Expected behavior**

Unpinned tabs to be closed when I turn on the extension.

**Screenshots**

![screenshot2](https://github.com/igorlogius/auto-close-tabs/assets/3018448/6ce5f537-68df-49e3-ab8b-6dac04b2801a)

**Desktop**
 - OS: ArchLinux
 - Browser: Firefox
 - Version: 124.0

**Additional context**

...

**Comment by igorlogius** [comment]
Thank you for reporting this issue. 
I am more than a little bit suprised that nobody else caught this yet. 

There was a typ error, when reading the unit value from storage and i did not catch that, because my test ignored that value to always speedup the processing time, for testing.

It should be fixed now in `1.7.11` 

Guess moral of the story is that i should not take to many shortcuts when testing, otherwise the test might not accurately represent the real world usage.

**Comment by cecton** [comment]
> I am more than a little bit suprised that nobody else caught this yet.

Yeah I think people rarely report issues. In OSS in general I mean. They're more like "it works I keep it, it doesn't I uninstall".

> Guess moral of the story is that i should not take to many shortcuts when testing

It's a very good lesson! Been there.

![2-unit-tests-0-integration-test-meme](https://media1.tenor.com/m/7c9bvnQbGCIAAAAd/unittest-unit.gif)

I had a colleague years ago who really hated unit testing. He said: "Actually we don't need unit tests at all!" So he was in favor of deleting all the unit tests and only keep the integration tests and even make more of them.

But the thing is, the integration tests were using Selenium and the CI took approximately 4 to 6 hours to complete. But that only if the tests pass and usually they failed pretty badly (selenium tests are easily very flaky).

So I guess he teach me the opposite lesson: being too pedantic about testing can be such a huge waste of time too. You need to find that right balance where your tests catches the most important parts without being a hassle for your team.

**Comment by cecton** [comment]
Thanks a lot for the update! I will report to you in a few days to see if things work well.

(Right now, all I can say is that it didn't close right away the existing tabs after I installed the update. Maybe I need to wait the 15 days again.)

**Comment by igorlogius** [comment]
> Thanks a lot for the update! I will report to you in a few days to see if things work well.

Thanks. That would be very helpful. 

> Right now, all I can say is that it didn't close right away the existing tabs after I installed the update

Please keep in mind, the relevant time closing time is calculated using the last time a tab was accessed/activated, meaning that if you frequently toggle between the tabs and have a higher close time it can very likely be that those tabs might seldomly to never close. 

Also i have to admit ... that i dont exactly know what happens when you close the browser and reopen the tabs later. Might just be that the access time is not retained, but reset, but i am not sure. And there is also the case for discarded tabs ... here i am also not sure if those retain their access time.  - These cases are something i ignored initally and might at somepoint have to revisit. 

So what i am trying to say is that if you restart your browser or you system frequently discards tabs then that might potentially also be a reason, why the tabs do not close.
