### ISSUE TITLE
Add Minutes to the Timeout dropdown

### ISSUE THREAD

**Issue by joel72265** [igorlogius/auto-close-tabs#5]
Thank you for this extension. This is a feature request, on reviewing, please can you add 'minutes' to the timeout as well. Thank you

**Is your feature request related to a problem? Please describe.**
Not related to a problem

**Describe the solution you'd like**
please add the option 'Minutes' to the 'Amount of time until a tab is closed' dropdown

**Describe alternatives you've considered**
other extensions

**Comment by igorlogius** [comment]
![Screenshot_2024-03-25_09-39-58](https://github.com/igorlogius/auto-close-tabs/assets/67047467/b104c62c-d810-43f9-b460-65dda2975ef7)

Already done with 1.7.11

**Comment by igorlogius** [comment]
Please be aware that the cleanup wakup interval is by design not exact - to not cause unnecessary strain on system resouces - so pease dont expect it to hit at the exact second mark a tab reaches it deprication.

And there might still be some dragons in regards to browser restarts and discarded tabs i havent yet discovered and tamed. - If you discover one, please let me know via a bug report!

**Comment by joel72265** [comment]
thank you for your prompt reply.

the tabs do close. Can you make the "Minimum number of tab...." to be zero instead of 1 (because pinned tabs are not counted if I am correct)

**Comment by igorlogius** [comment]
> thank you for your prompt reply.

no problem

>  Can you make the "Minimum number of tab...." to be zero instead of 1 (because pinned tabs are not counted if I am correct)

yeah, i can add that, just be aware, that when no pinned tab are present, this will close the entire browser window.

**Comment by igorlogius** [comment]
@joel72265 
Just as sidenote, but try to keep an issue as "on topic" as possible. Meaning, dont reuse/open issues for other discussion for independed addional requests/bugs. Rather open a new issue, that helps keeping these issues at least somewhat small(ish) and that allows maintainers/devs to focus at one thing at a time and if i/we have to stop work at a certain time it also helps us/me to later be able to quicker revisit an issue easier, since it is less to reread and understand. 

Please dont take this as a nitpicky or mean statement, but rather something you should also keep in mind if you open bug or feature issues on other open source projects in general.

**Comment by joel72265** [comment]
noted

you are correct, I can create another request
