### ISSUE TITLE
Default ON with browser restart

### ISSUE THREAD

**Issue by joel72265** [igorlogius/auto-close-tabs#8]
**Is your feature request related to a problem? Please describe.**
Every time the web browser is restarted, you need to enable the extension every time

**Describe the solution you'd like**
The extension should retain the previous setting 

**Describe alternatives you've considered**

**Additional context**

**Comment by igorlogius** [comment]
i did not make it the default behaviour because of potential data lose, but i can add a setting on the options page that makes the state persistent.

**Comment by joel72265** [comment]
I don't think there would be data loss but know best, especially for those that using the extension to specifically close tab automatically. thanks

**Comment by igorlogius** [comment]
Mmmh, i build the activation state on a "per Window" basis, this makes this request a bit more difficult.

**Comment by igorlogius** [comment]
![2024-03-29_16-04](https://github.com/igorlogius/auto-close-tabs/assets/67047467/00950b99-6923-464e-93f7-9edfaf707a61)

Have fun, dont come complaining if comething get closed, you did not want, since you ask for the addon to be auto activated in all windows per default. 

You can still make exclusions via the toolbar button.
